version: "3"

services:
    app:
        image: node:alpine
        container_name: Expenses-Chart
        working_dir: /usr/app
        ports:
            - 3000:3000
        volumes:
            - .:/usr/app
            - ./node_modules:/usr/app/node_modules
        entrypoint: npm run dev
